name: Auto Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

jobs:
  auto-merge:
    name: Auto Merge PR
    runs-on: ubuntu-latest
    
    # Only run if PR has 'auto-merge' label
    if: |
      github.event_name == 'pull_request' && 
      contains(github.event.pull_request.labels.*.name, 'auto-merge')
    
    steps:
      - name: Wait for CI checks
        uses: actions/github-script@v7
        with:
          script: |
            // Wait a bit to let other checks start
            await new Promise(resolve => setTimeout(resolve, 30000));
            
      - name: Enable auto-merge
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pull_number = context.payload.pull_request.number;
            
            try {
              await github.rest.pulls.merge({
                owner,
                repo,
                pull_number,
                merge_method: 'squash'
              });
              console.log(`Successfully merged PR #${pull_number}`);
            } catch (error) {
              console.log(`Auto-merge not ready yet: ${error.message}`);
            }